---
- name: Fail on unsupported platforms
  ansible.builtin.assert:
    that:
    - ansible_os_family in ['Debian', 'RedHat']
    fail_msg: >-
      This role supports Debian/Ubuntu and Red Hat family hosts only.
      Found ansible_os_family={{ ansible_os_family }}.

- name: Prepare Python dependencies
  ansible.builtin.include_tasks: virtualenv.yml

- name: Get the public IP address
  community.general.ipify_facts:

- name: Update the DNS record(s)
  amazon.aws.route53:
    state: present
    zone: "{{ item.zone }}"
    record: "{{ item.record }}"
    type: "{{ item.type | default('A') }}"
    ttl: "{{ item.ttl | default(omit) }}"
    value:
    - "{{ ansible_facts.ipify_public_ip }}"
    access_key: "{{ update_ip_r53_aws_access_key }}"
    secret_key: "{{ update_ip_r53_aws_secret_key }}"
    wait: "{{ item.wait | default(true) | bool }}"
    overwrite: true
  loop: "{{ update_ip_r53_records }}"
