---
- name: Install the virtualenv requirements (Debian)
  ansible.builtin.apt:
    name:
    - python3-pip
    - python3-virtualenv
    update_cache: true
    state: present
  when: ansible_os_family == 'Debian'

- name: Install the virtualenv requirements (Red Hat)
  ansible.builtin.yum:
    name:
    - python3-pip
    - python3-virtualenv
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install boto3 and botocore in a virtualenv
  ansible.builtin.pip:
    name:
    - boto3>=1.34.0
    - botocore>=1.34.0
    virtualenv: "{{ update_ip_r53_virtualenv_dir }}"
    # Keep system site-packages available for SELinux Python bindings.
    virtualenv_site_packages: true

- name: Use the created virtualenv
  ansible.builtin.set_fact:
    ansible_python_interpreter: "{{ update_ip_r53_virtualenv_dir }}/bin/python"
